### PR TITLE
Add Dockerfile and Docker Compose testing manifest.

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building. Mainly useful for quickly deploying.
Using the official [Caddy webserver](https://caddyserver.com/) image, latest tag. More info at https://hub.docker.com/r/abiosoft/caddy/

Just adding `index.html` to Caddy's default webroot dir, setting working dir and using default entrypoint.

Build:

```
$ docker build -t dashboard .
```

Run:

```
$ docker run --rm -it -p 80:2015 dashboard
```

FYI, there's a still quicker to test, already built image on my Docker Hub. Test it by running:

```
$ docker run --rm -it -p 80:2015 pataquets/healthchecks-dashboard
```

Using `--rm` instead of `-d` makes the container not go background and it to be deleted after stop. Should stop by `CTRL+C`'ing it.

Also, there is an example Docker Compose file I'm using to build/run/test it, which reproduces the above steps.

Optional improvement to come (maybe in another issue):
- Create an 'official', based on your repo, automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/ . Just requires a free Docker Hub account and a following a quick 'Create automated build' process. I'll be happy to help on it, if needed.

### CODE REVIEW

**Comment by cuu508** [comment]
Thanks for this! A couple questions:

* How about using joshix/caddy as a base? I did a quick experiment – it produces a 30MB smaller image. I'm not too familiar with Docker though, it could also be missing important features that I'm not aware of...

```
$ docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
dashboard-joshix    latest              e0c689db0c77        51 seconds ago      21.4MB
dashboard           latest              32cdc033598f        7 minutes ago       53.3MB
abiosoft/caddy      latest              f2eece677796        3 months ago        53.3MB
joshix/caddy        latest              5c6509cbaf32        7 months ago        21.4MB

```

* Could you also update README with instructions similar to the ones in this PR?

**Comment by pataquets** [comment]
Even at the expense of weighing a few more Mb (not that much, however), I'd stick to abiosoft's image, since it's more widespreadly used and more maintained. That is, until caddysoftware releases their own's for version 2: https://github.com/caddyserver/caddy-docker/blob/master/Dockerfile
About the docs, I can submit a commit also. However, I need the DH image URL first, for the example usage and links.
We can also add a cool 'docker pulls' badge to the readme, if you feel like it. ;)

**Comment by cuu508** [comment]
> Even at the expense of weighing a few more Mb (not that much, however), I'd stick to abiosoft's image, since it's more widespreadly used and more maintained. 

Ah, OK, sounds good. As I said, not an expert with this :-)

I'll merge this PR so I can set up a DH build, and we can update the README afterwards.

**Comment by cuu508** [comment]
Just set up a repository in Docker Hub: https://hub.docker.com/r/healthchecks/dashboard
This seems to work:

    docker run --rm -it -p 80:2015 healthchecks/dashboard

**Pull request merged**
